version: "3"
services:
  mysql:
    image: mysql:8
    env_file:
      - ./default.env
    volumes:
      - ./files/etc/mysql/conf.d:/etc/mysql/conf.d
      - ./files/init:/docker-entrypoint-initdb.d
    ports:
      - "${PORT:-3306}:3306"
    tmpfs:
      - /var/lib/mysql
      - /var/log/mysql

